<tr class="setting-postlist" id="<?php echo $wo['langs_'];?>">
   <td style="text-align: center;"><?php echo $wo['langs'];?></td>
   <td style="text-align: center;">
      <a class="pointer black" href="<?php echo Wo_LoadAdminLinkSettings('edit-lang?id=' . $wo['langs_']);?>"><i class="fa fa-pencil-square progress-icon" data-icon="trash-o"></i> 编辑</a> | 
      <span class="delete-field pointer black" onclick="Wo_DeleteLang('<?php echo $wo['langs_'];?>');"><i class="fa fa-trash-o progress-icon" data-icon="trash-o"></i> 删除</span>
   </td>
</tr>